name: Lint

on:
  workflow_call:

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1
  CLICOLOR_FORCE: 1

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11   # v4.1.1
    - name: Set up Python 3.12
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236   # v4.7.1
      with:
        python-version: '3.12'
        cache: pip
    - run: python -m pip install --constraint=.github/workflows/constraints.txt pip setuptools wheel hatch
    - name: Set up pre-commit cache
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84   # v3.3.2
      with:
        path: ~/.cache/pre-commit
        key: lint-${{ hashFiles('.pre-commit-config.yaml') }}
    - run: hatch run lint:all
